package com.mike.wordrank.api.config;

import java.io.File;
import java.io.IOException;

import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

import com.mike.wordrank.WordRank;

public class WordConfig implements Config {

	private FileConfiguration config;
	private File configFile;
	
	public WordConfig(WordRank plugin) {
		configFile = new File("plugins/WordRank/" + "words.yml");
		this.config = YamlConfiguration.loadConfiguration(configFile);
		config.set("WARNING", "Do NOT edit this file while WordRank is running. Changes may be lost!");
		
		if (!configFile.exists()) {
			WordRank.debug("words.yml not found, creating");
			try {
				config.save(configFile);
			} catch (IOException e) {
				WordRank.debug("Could not save words.yml");
				e.printStackTrace();
			}
		}
	}
	
	public Object getValue(String path) {
		return config.get(path);
	}
	
	public FileConfiguration getConfig() {
		return config;
	}
	
	public void setSave(String path, Object value) {
		config.set(path, value);
		save();
	}
	
	public void save() {
		try {
			config.save(configFile);
		} catch (IOException e) {
			WordRank.debug("Could not save words.yml");
			e.printStackTrace();
		}
	}
}