# This is the main configuration for WordRank
# 
# If you are interested to see the source code of this plugin, its API (yes it has one) you can view
#  it on GitHub here: https://github.com/mike101102/WordRank
# 
# This plugin uses Metrics, it will collect anonymous data about different plugins. If you would like
#  to opt out, you can do so by going to /plugins/PluginMetrics/config.yml and change opt-out to true
#  You can view the stats collected here: http://metrics.griefcraft.com/plugin/WordRank
# 
# Syntax for this config's options
#  redeem_type: [Chat|Command]
#  debug_mode: [true|false]
#  language: [EN_US|EN_CA|French|German|Spanish]

redeem_type: Chat
debug_mode: false
language: EN_US